# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbbd6424cf304c720beb519e4638ffb6"
application_url = "https://d3ab-2a01-cb0c-5c6-300-e073-2e12-e0a-6f29.ngrok-free.app"
embedded = true
name = "product-carousel-app"
handle = "product-carousel-app-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testboutiqueclient.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://d3ab-2a01-cb0c-5c6-300-e073-2e12-e0a-6f29.ngrok-free.app/auth/callback",
  "https://d3ab-2a01-cb0c-5c6-300-e073-2e12-e0a-6f29.ngrok-free.app/auth/shopify/callback",
  "https://d3ab-2a01-cb0c-5c6-300-e073-2e12-e0a-6f29.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
